### ISSUE TITLE
Script hangs when its trying to load.

### ISSUE THREAD

**Issue by Frilock100** [Nebulezz/WSBFinScrape#1]
Everything was working fine until one day it doesn't pass the loading screen.

Here is the error? Does it have to do with yfinance?

File "C:\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    data = data.json()
    return _default_decoder.decode(s)
    return Ticker(ticker).history(period=period, interval=interval,
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    data = data.json()
  File "C:\Python39\Lib\threading.py", line 954, in _bootstrap_inner
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    data = data.json()
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    return complexjson.loads(self.text, **kwargs)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    data = data.json()
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python39\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    self.run()
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\Lib\threading.py", line 954, in _bootstrap_inner
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
    raise JSONDecodeError("Expecting value", s, err.value) from None
    data = data.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    return callee(*args, **kwargs)
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
Traceback (most recent call last):
  File "C:\Python39\Lib\threading.py", line 954, in _bootstrap_inner
    data = data.json()
  File "C:\Python39\Lib\threading.py", line 892, in run
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    return _default_decoder.decode(s)
    return _default_decoder.decode(s)
    raise JSONDecodeError("Expecting value", s, err.value) from None
    raise JSONDecodeError("Expecting value", s, err.value) from None
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    self.run()
  File "C:\Python39\Lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    return Ticker(ticker).history(period=period, interval=interval,
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    data = data.json()
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    data = data.json()
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    self.run()
    return Ticker(ticker).history(period=period, interval=interval,
    return complexjson.loads(self.text, **kwargs)
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
    return complexjson.loads(self.text, **kwargs)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
  File "C:\Python39\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    data = data.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return _default_decoder.decode(s)
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
  File "C:\Python39\Lib\threading.py", line 892, in run
    return _default_decoder.decode(s)
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    return callee(*args, **kwargs)
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    data = data.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    self._target(*self._args, **self._kwargs)
    data = data.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
    data = data.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return Ticker(ticker).history(period=period, interval=interval,
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return callee(*args, **kwargs)
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    return _default_decoder.decode(s)
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    return Ticker(ticker).history(period=period, interval=interval,
    raise JSONDecodeError("Expecting value", s, err.value) from None
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    raise JSONDecodeError("Expecting value", s, err.value) from None
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    data = data.json()
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    data = data.json()
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
    raise JSONDecodeError("Expecting value", s, err.value) from None
    raise JSONDecodeError("Expecting value", s, err.value) from None
    return complexjson.loads(self.text, **kwargs)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    return _default_decoder.decode(s)
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "C:\Python39\lib\site-packages\yfinance\multi.py", line 179, in _download_one
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    return Ticker(ticker).history(period=period, interval=interval,
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\site-packages\yfinance\base.py", line 157, in history
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    data = data.json()
  File "C:\Python39\lib\site-packages\requests\models.py", line 897, in json
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KBraddie** [comment]
Hi, yeah it seems to be an issue with yfinance. Upgrading yfinance has fixed it for me. `pip install --upgrade yfinance` in the python terminal should work. Let me know if the issue persists!

**Comment by KBraddie** [comment]
Can you confirm whther updating Yfinance has fixed this issue? 

Cheers!
